The idea for the behaviour of these scripts directly comes from [[https://github.com/andreafrancia/trash-cli][trash-cli]]: I really like trash-cli, but I wanted to make modifications to the way it lists and allows the restoration of files and, because I do not use python, I decided to write shell scripts instead. This allows for extremely easy customization and tweaking based on personal preferences, and it allows to use the power of [[https://github.com/junegunn/fzf][fzf]].

These scripts are written for zsh, but require very minor editing to run in bash or other shells.

** Differences with trash-cli

- tra.sh uses [[https://github.com/junegunn/fzf][fzf]] to find trashed files/directories very easily from pattern, name, path, or date
- Files are listed chronologically (in reverse chronological order so that the last deleted file/directory is the easiest to access)
- Trashed directories are marked with "D" to distinguish them from trashed files
- All files in ~$HOME/.local/share/Trash/files~ are listed, even if their meta data in ~$HOME/.local/share/Trash/info~ is missing for whatever reason
- It is possible to list and restore only the files which were trashed from the current directory ([[https://github.com/andreafrancia/trash-cli][trash-cli]]'s behaviour), but it is also possible to list all files/directories in the trash and restore any of them from any directory
- Trashed files can be previewed with [[https://github.com/junegunn/fzf][fzf]]
- All trashed files go to the user's trash

** Requirements

These scripts require [[https://github.com/junegunn/fzf][fzf]].

** Installation

Simply clone this repository or copy these scripts in your ~$PATH~.

** Usage

Simply run any of the scripts from the command line (or from ranger, rofi, or your usual way to run commands).

You might want to set aliases (in your ~.zshrc~ file, or ~alias.zsh~ file, or ~.bashrc~ file, or wherever you normally define shell aliases). That way, you only have to call the alias to run the corresponding script.

I personally use these aliases:

**** List trashed files/directories

***** List all trashed files/folders
#+BEGIN_src sh
alias tls='zsh /home/marie/bin/my_bin/tra.sh/tra_ls.sh'
#+END_src

***** List only the files/folders trashed from the current directory
#+BEGIN_src sh
alias tlsd='zsh /home/marie/bin/my_bin/tra.sh/tra_ls_dir.sh'
#+END_src

***** List all trashed files/folders with preview
#+BEGIN_src sh
alias tlsp='zsh /home/marie/bin/my_bin/tra.sh/tra_ls_p.sh'
#+END_src

***** List files/folders trashed from the current directory with preview
#+BEGIN_src sh
alias tlsdp='zsh /home/marie/bin/my_bin/tra.sh/tra_ls_dir_p.sh'
#+END_src

**** Restore trashed files/directories

#+BEGIN_src sh
# Restore any file/folder
alias trs='zsh /home/marie/bin/my_bin/tra.sh/tra_rs.sh'

# Restore file/folder trashed from current directory
alias trsd='zsh /home/marie/bin/my_bin/tra.sh/tra_rs_dir.sh'

# Restore any file/folder with preview
alias trsp='zsh /home/marie/bin/my_bin/tra.sh/tra_rs_p.sh'

# Restore file/folder trashed from current directory with preview
alias trsdp='zsh /home/marie/bin/my_bin/tra.sh/tra_rs_dir_p.sh'
#+END_src

**** Clean trash

#+BEGIN_src sh
# Permanently delete all files/directories in the trash
alias tcl='zsh /home/marie/bin/my_bin/tra.sh/tra_cl.sh'

# Only delete files/directories in the trash which are n days old or older
alias tcld='zsh /home/marie/bin/my_bin/tra.sh/tra_cl_date.sh'
# Add the number of days after this command
# For example, in order to delete all files/directories 3 days old or older, type:
# tcld 3
#+END_src
